#FROM mintplexlabs/anythingllm
#FROM forceless/pptagent
#FROM node:slim
#ENV NODE_VERSION=23.9.0
#ENV YARN_VERSION=1.22.22
#FROM node:latest
#FROM node:18.20.5
#FROM node:18.20.5-slim
FROM tabbyml/tabby:nightly
